### PR TITLE
Boards sidebar navigation menu

### PR DESCRIPTION
**Pull request by darkksuns**
Completed the navbar!
It has a resize bar on the side which you can drag to change the width of the bar. Any content that doesn't fit into the bar will have a ... after it as well.
Close and open buttons work with a smooth animation coming out from the side.
Sidebar opens at 250px wide and has a minimum of 140px (so the text "Your Boards" doesn't cut off.

image
image

**Quick thing:** as long as we are okay with the smoothness of the adjustment bar then it should be fine.
Currently when adjusting the bar, if you move quickly the bar will adjust pretty smoothly but if you make sudden movements it has a more snappy adjustment which I think is not awful (can fix it later if we get time kinda thing).

Also the sidebar will always open at 250px which I think is better than saving the adjusted sidebar width (as its unlikely to be open a lot of the time) but if any of you think otherwise please let me know.

### CODE REVIEW

**Comment by Ciaranengelbrecht** [comment]
Awesome I think this design looks real clean, the animation is seamless for me, and I think the default width is ideal

**Review by DJRyLau — APPROVED** [review]
Super clean, and the ability to resize it is unexpectedly fun to use! My only reccomendation is to have the 'Your Boards' not collapse to be on top of each other when closing the tab.
Screenshot 2024-05-09 163722
I'd much prefer if it behaved similarly to the Example Boards you have there. Not sure if this is just a me thing, would like other peoples input in this. Otherwise, I think this is a great start!

**Comment by darkksuns** [comment]
@DJRyLau idk how but I really struggled to make that boards menu have the ... like the boards
I'll give it another go later today though thanks for the suggestion.

**Comment by DJRyLau** [comment]
> @DJRyLau idk how but I really struggled to make that boards menu have the ... like the boards I'll give it another go later today though thanks for the suggestion.

No sweat. After all, if the issue cant be resolved, there's no harm in merging now and making it a seperate issue for the rest of us to look at.

**Review by HenryHewgill — CHANGES_REQUESTED** [review]
I like the sidebar & resizing, that's nice! I'd do some things differently though:
- Just use 'Boards' as the title, not 'Your Boards',
- Sidebar button can be added to the top-nav, positioned on the left, rather than sitting in its own space,
- Sidebar opening button doesn't follow down the page anymore, which I thought was clean & I liked it centered. I imagined it working like the ChatGPT interface:
# Desktop
Screenshot 2024-05-09 at 11 06 36 pm
Screenshot 2024-05-09 at 11 06 44 pm

# Mobile
Screenshot 2024-05-09 at 11 07 22 pm
Screenshot 2024-05-09 at 11 07 38 pm

Let me know what you guys think, on the note-design branch I've added the sidebar opening / closing button to the top-nav (it's not hidden yet for larger displays) if you want to see what that's like

**Comment by darkksuns** [comment]
@HenryHewgill I can try to implement that > becoming < button thing like on chatgpt but i think its better from a UX perspective because the rest of the page will be cluttered with notes that the close button should be on the bar itself. Otherwise it would be a bit cluttered and may blend in with the page content etc.

I changed the name from Your Boards to Boards and also added that > button into the navbar div and added a bit of padding to the navbar so it's not super up in the corner of the screen.

Even though I restructured the branch it still has merge conflicts though so I'll give it a look now

**Review by HenryHewgill — APPROVED** [review]
@darkksuns good point about the '<' overlapping the notes & being potentially hard to distinguish, that makes sense. Happy to go with the navbar buttons & close button in the top corner, that makes sense & is definitely enough for MVP.

**Pull request merged**
